name: Daily Job Scraper

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6 AM UTC
  workflow_dispatch:      # Allowing manual run

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the scraper
        run: python scraper.py

      - name: Commit and push CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output.csv
          git commit -m "Daily scrape update $(date)"
          git push
